- name: Configure SSH
  hosts: all
  become: yes
  tasks:
    - import_tasks: tasks/ssh.yml

- name: Set environment
  hosts: all
  become: yes
  tasks:
    - import_tasks: tasks/environment.yml

- name: Update and install common packages
  hosts: all
  become: yes
  tasks:
    - import_tasks: tasks/software.yml

- name: Provision pi (1/2)
  hosts: pi
  become: yes
  tasks:
    - package:
        name: "{{ pi_packages }}"
        state: latest

- name: Provision pi (2/2)
  hosts: pi
  become: yes
  tasks:
    - pip:
        name: docker

- name: Samba initialization
  hosts: pi
  become: yes
  tasks:
    - import_tasks: tasks/samba.yml

- name: Enable Docker service
  hosts: pi
  become: yes
  tasks:
    - systemd:
        name: "docker"
        state: "started"
        enabled: true

- name: Start Docker containers
  hosts: pi
  become: no
  tasks:
    - import_tasks: tasks/docker.yml