- name: Install software (air) 2/2
  hosts: air
  become: no
  tasks:
    - homebrew:
        name: homebrew/cask/docker
        update_homebrew: yes
        upgrade_all: yes

- name: Wait for Docker Desktop launch
  tasks:
    - pause:
        prompt: "Verify that Docker Desktop is running."

# fatal: [air]: FAILED! => {"changed": false, "msg": "Warning: Cask 'docker' is already installed.\n\nTo re-install docker, run:\n  brew reinstall --cask docker"}